Superfast loaders
UnseenFaith/komada pull request #163
Opened 2017-03-20 10:39 UTC by kyranet

### Proposed Semver Increment Bump: [MAJOR]

Loading times:
108 commands, (~10.200loc) 35s => 6s (5.8x faster)
78 commands, (~6.400loc) 24s => 5s (4.8x faster)

### Changes Proposed in this Pull Request (List new items in CHANGELOG.MD)

- Faster loading times

2017-03-20 13:34 UTC, kyranet commented
I added a last change, deleting the file from the cache after loading the pieces. By that, I could reduce 5MB worth of data from the cache with this.

On my point of view, I don't think we need the same data cached in both `require.cache` and `client.CollectionOfPieces`. I also thought this change *may* break the reload command, but I have just tested and it doesn't return an error.

2017-03-21 01:30 UTC, kyranet commented
According to the reload command. 

- Reload command: **OK!**
- Reload monitor: **OK!**
- Reload inhibitor: **OK!**
- Reload function: **OK!**

Memory usage seems to be better, dropped 8MB with all the previous PRs (now using 41MB vs 49MB). As well as the loading time is now faster since we removed a bunch of useless functions. ¯\\\_(ツ)\_/¯

2017-03-21 01:38 UTC, kyranet commented
Lastest commit fixes the issue #158.

2017-03-21 02:21 UTC, CyberiumShadow requested changes

2017-03-21 02:21 UTC, CyberiumShadow commented on functions/awaitMessage.js
> +  const user = msg.author || msg.member;
shouldn't it be `const user = msg.member || msg.author;` ?

2017-03-21 02:23 UTC, kyranet commented on functions/awaitMessage.js
> +  const user = msg.author || msg.member;
Updated.

2017-03-21 02:24 UTC, CyberiumShadow approved these changes

2017-03-21 02:31 UTC, merged