Arg resolver cleanup
UnseenFaith/komada pull request #237
Opened 2017-05-27 05:39 UTC by bdistin

### Proposed Semver Increment Bump: [MAJOR/MINOR/PATCH]
patch
### Changes Proposed in this Pull Request (List new items in CHANGELOG.MD)

-
-
-

### (If Applicable) What Issue does it fix?
 Fixes... uncached users/members from failing checks (fetches them if not cached)

2017-05-27 05:55 UTC, UnseenFaith submitted a review, later dismissed
lgtm

2017-05-27 06:18 UTC, kyranet commented on classes/argResolver.js
> +      (regex.userOrMember.test(arg) ? this.client.users.get(regex.userOrMember.exec(arg)[1]) : undefined);
This regex is being processed twice.

2017-05-27 08:25 UTC, kyranet requested changes
There are some changes that won't work as expected.

2017-05-27 08:25 UTC, kyranet commented on classes/Resolver.js
> +    if (string instanceof String) return true;
Resolver#string is supposed to return a string, not boolean.

2017-05-27 08:25 UTC, kyranet commented on classes/Resolver.js
> +    if ([0, "false", "-", "f"].includes(bool)) return false;
`[1].includes("1");` returns false. Both 1 and 0 must be instringified.

2017-05-27 08:25 UTC, kyranet commented on classes/Resolver.js
> +    if ([0, "false", "-", "f"].includes(bool)) return false;
Same for the case in false.

2017-05-27 08:25 UTC, kyranet commented on classes/Resolver.js
> +    if (member instanceof String) return regex.userOrMember.test(member) ? guild.fetchMember(regex.userOrMember.exec(member)[1]).catch(() => null) : null;
member instanceof String will always return false, unless doing a previous `String(member);`. However, `member.constructor.name === "String";` works perfectly.

2017-05-27 08:25 UTC, kyranet commented on classes/Resolver.js
> +    if (channel instanceof String) return regex.channel.test(channel) ? this.client.channels.get(regex.channel.exec(channel)[1]) : null;
Same here.

2017-05-27 08:25 UTC, kyranet commented on classes/Resolver.js
> +    if (guild instanceof String) return regex.snowflake.test(guild) ? this.client.guilds.get(guild) : null;
Here...

2017-05-27 08:25 UTC, kyranet commented on classes/Resolver.js
> +    if (role instanceof String) return regex.role.test(role) ? guild.roles.get(regex.role.exec(role)[1]) : null;
And here.

2017-05-27 08:25 UTC, kyranet commented on classes/Resolver.js
> +    if (user instanceof String) {
Here too.

2017-05-27 15:09 UTC, kyranet submitted a review, later dismissed

2017-05-27 15:12 UTC, kyranet submitted a review, later dismissed
Looks good now.

2017-06-03 18:27 UTC, kyranet requested changes
I know all methods are async to keep consistency, but I think it's not needed if we don't use async operations.

2017-06-03 18:27 UTC, kyranet commented on classes/Resolver.js
> +    if (guild instanceof Discord.Channel) return guild;
Shouldn't this be instanceof Discord.Guild?

2017-06-03 18:27 UTC, kyranet commented on classes/Resolver.js
> +    if (typeof string === "string") return string;
In both ways, it returns a String. Why not just `return String(string);`.

2017-06-03 18:27 UTC, kyranet commented on classes/argResolver.js
> +    const max = currentUsage.possibles[possible].max;
You can use deconstruction here. `const { max } = currentUsage.possibles[possible];`

2017-06-03 18:27 UTC, kyranet commented on classes/argResolver.js
> +    const max = currentUsage.possibles[possible].max;
Same here.

2017-06-03 18:27 UTC, kyranet commented on classes/argResolver.js
> +    if (!currentUsage) return null;
Isn't this always present?

2017-06-03 18:35 UTC, kyranet commented
To be honest, only the member parser needs async/await, as it fetchs the user and then the member, but the rest returns either a promise or the output, slowing down the parser for the async methods isn't the ideal, when only user and member can return a Promise.

2017-06-04 14:13 UTC, bdistin commented on classes/argResolver.js
> +    if (!currentUsage) return null;
It isn't... The parent class calls user internally, but since it is extended, the parent call calls the child class...

2017-06-04 14:20 UTC, kyranet commented on classes/argResolver.js
> +    if (!currentUsage) return null;
Well, it's wasn't present on the rest of functions.

2017-06-04 15:09 UTC, Josefied commented
Good stuff here!

2017-06-04 19:01 UTC, kyranet submitted a review, later dismissed
LGTM.

2017-06-05 02:04 UTC, CyberiumShadow approved these changes
Tested. LGTM

2017-06-05 02:05 UTC, merged