Update log.js and package.json cleanup
UnseenFaith/komada pull request #257
Opened 2017-06-06 18:55 UTC by dada1134

### Proposed Semver Increment Bump: [MAJOR/MINOR/PATCH]

Minor

### Changes Proposed in this Pull Request (List new items in CHANGELOG.MD)

- add an option to disable timestamps in logs
- log now adds the timestamp to every line
- reorder package.json and add `homepage` field

### (If Applicable) What Issue does it fix?

Nothing

2017-06-06 19:09 UTC, UnseenFaith submitted a review, later dismissed
Few things.
A) I don't think we need an extra module to do padding. 
B) There should be a configuration option to disable color instead of just removing it automatically.

2017-06-06 19:12 UTC, dada1134 commented
> I don't think we need an extra module to do padding.

Here's a good explanation on why I did that @UnseenFaith: https://github.com/sindresorhus/ama/issues/10#issuecomment-117766328

2017-06-06 19:27 UTC, bdistin requested changes

2017-06-06 19:27 UTC, bdistin commented on package.json
> +    "lpad": "^2.0.1",
.padEnd() .padStart() are available native in node V8.0.0.

You do not need a package for this functionality...

2017-06-06 20:45 UTC, bdistin requested changes

2017-06-06 20:45 UTC, bdistin commented on inhibitors/requiredFuncs.js
> +  if (funcs.length > 0) return `The client is missing the **${funcs.join(", ")}** function and cannot run.`;
Multiple functions can be missing.

2017-06-06 20:45 UTC, bdistin commented on events/log.js
> +  console[type](data.split("\n").map(str => str.padStart(timestamp.length + str, timestamp)).join("\n"));
First Arg of padStart should be a number. Adding a number to a string makes it a string. (drop ` + str` to be correct)... But doing that is pointless, you should be concatenating here with template literals.

2017-06-06 20:45 UTC, bdistin commented on events/log.js
> +    timestamp = moment().format("YYYY-MM-DD HH:mm:ss ");
You have dropped the [] wrapping the timestamp. Please add it back.

2017-06-06 21:12 UTC, dada1134 commented on events/log.js
> +  console[type](data.split("\n").map(str => str.padStart(timestamp.length + str, timestamp)).join("\n"));
I'm not sure how you wanted to fix it but I fixed it and tested it.

2017-06-06 21:13 UTC, bdistin commented on events/log.js
> +  console[type](data.split("\n").map(str => str.padStart(timestamp.length + str, timestamp)).join("\n"));
data.split("\n").map(str => timestamp + str).join("\n")

2017-06-06 21:19 UTC, dada1134 commented on events/log.js
> +  console[type](data.split("\n").map(str => str.padStart(timestamp.length + str, timestamp)).join("\n"));
Haha of course, that's way simpler!

2017-06-06 21:34 UTC, bdistin submitted a review, later dismissed
👍

2017-06-07 14:12 UTC, kyranet commented on inhibitors/requiredFuncs.js
> +  if (funcs.length > 0) return `The client is missing the **${funcs.join(", ")}** ${funcs.length > 1 ? "functions" : "function"} and cannot run.`;
You can also do 

```js
`function${funcs.length > 1 ? "s" : ""} and cannot run.`

2017-06-07 14:16 UTC, kyranet submitted a review, later dismissed
👍

2017-06-08 21:03 UTC, CyberiumShadow approved these changes

2017-06-08 21:03 UTC, merged