The Lord of the Evals
UnseenFaith/komada pull request #368
Opened 2017-10-09 01:51 UTC by tech6hutch

Three Evals for the Elven-kings under the sky,
Seven for the Dwarf-lords in their halls of stone,
Nine for Mortal Men doomed to die,
One for the Pull Requester on his dark fork
In the Land of Komada where the Shadows lie.
One Eval to rule them all, One Eval to find them,
One Eval to bring them all and in the darkness bind them
In the Land of Komada where the Shadows lie.

Note: I haven't actually tested the Komada version yet, but here's my quick port.

### Proposed Semver Increment Bump: [MAJOR/MINOR/PATCH]
MINOR

### Changes Proposed in this Pull Request (List new items in CHANGELOG.MD)

* Know the exact type of what you evaled
  * Has a little notice if it's a boolean, number, or string instantiated with `new` (see [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#Distinction_between_string_primitives_and_String_objects))
  * Notes when a promise has been `await`ed, and what its resolved value is
* Know how long the eval took to execute
  * Unit may be seconds, milliseconds, or microseconds, depending on the scale of the duration, for enhanced readability
* New flags for deleting your command message, logging the output to console instead of sending it to the channel, and doing the command silently without output
* If the output is long (7+ lines, or having long lines that will wrap), it asks before posting it to the channel
* If the output is too long to send (>2000 chars), it asks if you want to log it to the console or upload it as a file

### (If Applicable) What Issue does it fix?

 Fixes... 
* The eval command silently erring if the output is more than 2000 characters

2017-10-09 22:13 UTC, CyberiumShadow commented on src/commands/System/eval.js
> +const inspectionDepth = 0;
Make these into clientOptions tbh.

`client.config.eval.inspectionDepth` etc

2017-10-09 22:16 UTC, CyberiumShadow requested changes

2017-10-09 22:16 UTC, CyberiumShadow commented on src/commands/System/eval.js
> +const inspectionDepth = 0;
Make these into a clientConfig option

`client.config.eval.inspectionDepth` etc

2017-10-09 22:16 UTC, CyberiumShadow commented on src/commands/System/eval.js
> +const typeRecursionLimit = 2;
and here

2017-10-09 22:16 UTC, CyberiumShadow commented on src/commands/System/eval.js
> +const tooManyLines = 7;
and here

2017-10-09 22:16 UTC, CyberiumShadow commented on src/commands/System/eval.js
> +const mobileCharsPerLine = 34;
and here

2017-10-10 23:05 UTC, CyberiumShadow commented
DIscussed in staff chat. Preferable to move this to the dirigeants/komada-pieces repo

2017-10-15 22:54 UTC, tech6hutch commented
👌 gonna commit a simpler version, like I did on Klasa, and PR this version to Komada Pieces

2017-11-20 11:52 UTC, merged